

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: midb
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/docker-entrypoint-initdb.d/data
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
